### ISSUE TITLE
Cannot install via pip

### ISSUE THREAD

**Issue by mhaas** [SelfDestroyer/pyMOD-OLED#2]
I'm getting this error:

```
(oled)laga@ivanov:~/venv$ pip install mod-oled-128x64
Downloading/unpacking mod-oled-128x64
  Downloading mod-oled-128x64-0.0.3.tar.gz
  Running setup.py (path:/tmp/pip-build-BJhdn1/mod-oled-128x64/setup.py) egg_info for package mod-oled-128x64
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-BJhdn1/mod-oled-128x64/setup.py", line 21, in <module>
        long_description=read('README.rst') + '\n' + read('CHANGES.rst'),
      File "/tmp/pip-build-BJhdn1/mod-oled-128x64/setup.py", line 11, in read
        with open(path.join(here, name), encoding='utf-8') as f:
      File "/home/laga/venv/oled/lib/python2.7/codecs.py", line 878, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-BJhdn1/mod-oled-128x64/CHANGES.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-BJhdn1/mod-oled-128x64/setup.py", line 21, in <module>

    long_description=read('README.rst') + '\n' + read('CHANGES.rst'),

  File "/tmp/pip-build-BJhdn1/mod-oled-128x64/setup.py", line 11, in read

    with open(path.join(here, name), encoding='utf-8') as f:

  File "/home/laga/venv/oled/lib/python2.7/codecs.py", line 878, in open

    file = __builtin__.open(filename, mode, buffering)

IOError: [Errno 2] No such file or directory: '/tmp/pip-build-BJhdn1/mod-oled-128x64/CHANGES.rst'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-BJhdn1/mod-oled-128x64
Storing debug log for failure in /home/laga/.pip/pip.log
```

Thanks! Installation via the git repository works:

pip install git+https://github.com/SelfDestroyer/pyMOD-OLED.git

**Comment by selfbg** [comment]
CHANGES file was not uploaded on pypi. Now should be fixed.
Thanks for the feedback!
